Lab 1
Lemon4ik94/Borbych-Oleg-IPZ-32 pull request #1
Opened 2023-09-09 06:09 UTC by Lemon4ik94

Lab 1 ready to review

2023-09-13 18:52 UTC, vozniuk-lntu requested changes

2023-09-13 18:52 UTC, vozniuk-lntu commented on index.html
> +        <a href="#">Студія</a>
список посилань

2023-09-13 18:52 UTC, vozniuk-lntu commented on index.html
> +      <a href="mailto:info@devstudio.com" title="info@devstudio.com"
список посилань

2023-09-13 18:52 UTC, vozniuk-lntu commented on index.html
> +      <div class="title">
title не камільфо юзати для чогось крім заголовків
цю секцію прийнято називати hero (секція яка відразу під хедером)
і це не дів а `section`

2023-09-13 18:52 UTC, vozniuk-lntu commented on index.html
> +      <div>
section

2023-09-13 18:52 UTC, vozniuk-lntu commented on index.html
> +          <h2>Чим ми займаємось</h2>
це окремо в секцію

2023-09-13 18:52 UTC, vozniuk-lntu commented on index.html
> +          <h2>Наша команда</h2>
команду в секцію теж

2023-09-13 19:11 UTC, vozniuk-lntu commented
в тебе в main має бути чотири section

2023-09-13 19:12 UTC, vozniuk-lntu requested changes
комент про мейн глянь
не уважно дивився

2023-09-13 19:15 UTC, Lemon4ik94 commented
> в тебе в main має бути чотири section

Так в мене 4 секції в мейні

2023-09-13 19:24 UTC, vozniuk-lntu requested changes
https://i.imgur.com/otla9MA.png

2023-09-13 19:28 UTC, Lemon4ik94 commented
> https://i.imgur.com/otla9MA.png

https://i.imgur.com/EpwRWgy.png

2023-09-15 10:56 UTC, vozniuk-lntu commented
https://i.imgur.com/SAubxeI.png оце виправити
зливай в мейн
перевір чи деплоїться
нову гілку з мейн робиш
наступна лаба
https://docs.google.com/document/d/1THT3lT1JlDAHJNTSdngiToexdVmUeLbE/edit?usp=sharing&ouid=104518963218417128491&rtpof=true&sd=true
і скрін як буде виглядати (працюєш суто з шрифтами та кольорами)
https://i.imgur.com/tniDQxh.png

2023-09-15 10:56 UTC, vozniuk-lntu approved these changes

2023-09-15 11:07 UTC, merged