Lab 3
Lemon4ik94/Borbych-Oleg-IPZ-32 pull request #3
Opened 2023-10-11 13:16 UTC by Lemon4ik94

2023-10-12 19:31 UTC, vozniuk-lntu requested changes
1. це падінг наступної секції https://i.imgur.com/vlIfeLS.png
2. очищай крайню геометрію https://i.imgur.com/Huwowes.png
3. відступ між сусідами це маржин https://i.imgur.com/IOTTd3u.png
4. просто клас. робиш відступ між секціями маржином спискку всередині секції https://i.imgur.com/SYCqiTs.png. Це теж падінг секції
5. тут тоже це падінг секції https://i.imgur.com/ixCcdVE.png
6. відступ між сусідами - маржин https://i.imgur.com/KCe5zqS.png. Порівняй розмір картинки в макеті і свою
7. тут майже. Цей падінг на секцію https://i.imgur.com/6OCxcf1.png
8. оце похоже на макет https://i.imgur.com/sWpLAkP.png. Серйозно?
9. без коментарів https://i.imgur.com/fpDccQK.png

2023-10-12 19:31 UTC, vozniuk-lntu commented on index.html
> +				<h2 class="development-stack-header">Чим ми займаємось</h2>
нащо тут флекс, відцентрувати текс просто

2023-10-12 19:31 UTC, vozniuk-lntu commented on index.html
> +			<address class="contact-info-footer">
ніякий тут не вертикальний флекс
і так блоково одне під одне можна вистроїти, переробити

2023-10-12 19:31 UTC, vozniuk-lntu commented on portfolio.html
> +                            <h3 class="project-title">Технокряк</h3>
обгорни заголовок і текст в дів і задай на дів падінги
а своє безобразіє прибери

2023-10-12 19:31 UTC, vozniuk-lntu commented on portfolio.html
> +                <ul class="project-list">
грід то є, але не правильний
на парі покажу як треба
ось підказка шо не так https://i.imgur.com/eEs4WUx.png
пустий оцей простір

2023-10-14 08:48 UTC, Lemon4ik94 commented
ez approve

2023-10-14 09:14 UTC, vozniuk-lntu approved these changes
1. додати габарити в картинки

2023-10-14 09:14 UTC, vozniuk-lntu commented on css/styles.css
> +    padding: 94px 0px;
не треба цей стиль на контейнер. Додай на секцію клас і туди ці падінги

2023-10-14 12:13 UTC, merged